spring:
  profiles:
    active: dev
  datasource:
    # 注意：MySQL连接驱动和版本都是8.0以上需要添加时区：serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
dbType: mysql
# 表空间
schema: test
# 模板公共路径
templateFolderPath: D:\devil13th\github\com-thd-springboot-framework-parent\com-thd-springboot-framework-generator\src\main\resources\template\ssm\
#  生成文件公共路径
targetFolderPath: D:\deleteme\cg\
# 包配置
coding:
  servicePackageName: com.thd.springboot.framework.example.service
  mapperPackageName: com.thd.springboot.framework.example.mapper
  controllerPackageName: com.thd.springboot.framework.example.controller
  entityPackageName: com.thd.springboot.framework.example.entity
# 自定义的属性 - map类型

custom:
  map:
    name: codeGen
    version: 1.0





logging:
  config: classpath:logback-spring.xml
  path: D:/deleteme/logbacks

